package com.aienglishcoach.core.domain.model

import kotlinx.datetime.Instant

/**
 * A practice exercise, usually generated by the AI from a detected [UserError].
 */
data class Exercise(
    val id: Long = 0,
    val type: ExerciseType,
    /** The task shown to the learner, e.g. a sentence with a gap. */
    val question: String,
    /** Answer options for [ExerciseType.MULTIPLE_CHOICE]; empty otherwise. */
    val options: List<String> = emptyList(),
    val correctAnswer: String,
    /** Explanation displayed after answering. */
    val explanation: String,
    /** Error this exercise was generated from; null for generic exercises. */
    val sourceErrorId: Long? = null,
    val srs: SrsState,
    val createdAt: Instant,
)

enum class ExerciseType {
    /** Fill in the missing word(s) in a sentence. */
    FILL_GAP,

    /** Choose the correct answer from [Exercise.options]. */
    MULTIPLE_CHOICE,

    /** Translate a Polish sentence into English. */
    TRANSLATION,

    /** Say the sentence out loud; checked via speech recognition. */
    SPEAKING,
}

/** A single attempt at solving an exercise. */
data class ExerciseAttempt(
    val id: Long = 0,
    val exerciseId: Long,
    val userAnswer: String,
    val isCorrect: Boolean,
    val attemptedAt: Instant,
)
